### ISSUE TITLE
Cannot process unexpected page "" - login failed?

### ISSUE THREAD

**Issue by sinksc** [ojehle/H35_OraclePatchDownloader#12]
Now that My Oracle Support has been updated and displays a two-page login experience, this script, as of version `oraclePatchDownloader-1.0.4.jar`, is failing with the error: `Cannot process unexpected page "" - login failed?`

**Comment by farblos** [comment]
MOS updated, again?  Sigh.  Will check.

**Comment by farblos** [comment]
OK, that's that new IDCS login procedure.  Very JavaScript-heavy, if we get that to work we have a unique selling point :-). Well, not quite, getMOSPatch continues to work :-(, most likely because of that totally uncool wget-based user agent.

Problem here is that so far I couldn't get the JavaScript to work.

- One has to trigger the form named `idcs-clp-signin-idp-redirect-form` on the page where things stopped working, for @sinksc  as well as for me.
- But then one of these huge JavaScripts (`signinModule/signin.js`) errors out with a syntax error.

Here is what I've tried so far after some initial googling:

- Using `BrowserVersion.EDGE` and `.CHROME`
- `webClient.waitForBackgroundJavaScript(10000);`
- `webClient.getOptions().setThrowExceptionOnScriptError(false);`

That results in a `400 Bad Request for https://signon.oracle.com/signin`.  Obviously, just ignoring the syntax error is not the right thing here.

Will continue playing around, if others have more/other ideas, pls let me know!

**Comment by farblos** [comment]
Hang on, things look better already ... I get a login page prompting for the user now.  Will continue tomorrow.

**Comment by ojehle** [comment]
i got the errors on thursday night with my account, so i planned to investigate the problem on monday.. .but good that you already debug the problem. i expect that the javascript errors can only be resolved by the framework used..

did you upgrade htmlunit already to 4.1.0? 

https://mvnrepository.com/artifact/org.htmlunit/htmlunit/4.1.0 

as i'm traveling, i cannot test it.

**Comment by farblos** [comment]
> did you upgrade htmlunit already to 4.1.0?

I already upgraded from 3.11.0 to 4.0.0, and - after your hint - to 4.1.0.  I think the upgrade from 3.11.0 to 4.\*.\* indeed made a difference.

But there is a big "BUT" + surprise: I tried to set the user agent string to `"Wget/1.21.3"` and provide user and password using basic authentication and - tadaaa - everything works a lot faster and easier, without all these CSS and JavaScript files getting downloaded first.  (I simply had to try that after I noticed that getMOSPatch still works, regardless of the MOS changes.)

Of course, this is a 180° turn to our current philosophy ("we are unique because we use JavaScript") but I wouldn't mind sacrificing that when things get easier *and* faster.  @ojehle, I hope you don't mind either.

I think what actually make sense here is to use the best of both worlds: First try authenticating with basic authentication and, if that fails, go for the heavy-weight, JavaScript based authentication.  That way we will be ready when Oracle decides to drop wget support.

I will push and merge a PR with the basic authentication changes soon, they are really rather simple.  Later I will brush up that whole login code and implement the JavaScript-based authentication for the new MOS login procedure.

**Comment by farblos** [comment]
Pushed the changes.

@sinksc, could you please test as well?  Either by building from source or by using the artifact from [this action run](https://github.com/ojehle/H35_OraclePatchDownloader/actions/runs/8950043270).

Thanks!

**Comment by ojehle** [comment]
when i start do wrote this downloader, my focus was only to have a tool to download a list of patches, because getmospatch was not working anymore. the most important thing is that it works, not philosophy.i‘m not surprised if in the future oracle will change again the interface. hopefully in the right direction, for example a rest interface for the patch search/download functionalityi will test monday and give feedback Am 04.05.2024 um 12:43 schrieb farblos ***@***.***>:﻿

did you upgrade htmlunit already to 4.1.0?

I already upgraded from 3.11.0 to 4.0.0, and - after your hint - to 4.1.0.  I think the upgrade from 3.11.0 to 4.*.* indeed made a difference.
But there is a big "BUT" + surprise: I tried to set the user agent string to "Wget/1.21.3" and provide user and password using basic authentication and - tadaaa - everything works a lot faster and easier, without all these CSS and JavaScript files getting downloaded first.  (I simply had to try that after I noticed that getMOSPatch still works, regardless of the MOS changes.)
Of course, this is a 180° turn to our current philosophy ("we are unique because we use JavaScript") but I wouldn't mind sacrificing that when things get easier and faster.  @ojehle, I hope you don't mind either.
I think what actually make sense here is to use the best of both worlds: First try authenticating with basic authentication and, if that fails, go for the heavy-weight, JavaScript based authentication.  That way we will be ready when Oracle decides to drop wget support.
I will push and merge a PR with the basic authentication changes soon, they are really rather simple.  Later I will brush up that whole login code and implement the JavaScript-based authentication for the new MOS login procedure.
